### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by christopherredden** [cmusphinx/pocketsphinx-ios-demo#1]
Hey,

I've cloned the latest from sphinxbase and pocketsphinx and built for armv7 using this build script. While sphinxbase configures and builds fine, pocketsphinx does not.

During configuration it complains as such:

> checking for sphinxbase in /Users/topher/Dev/pocketsphinx/scratch/armv7//Users/topher/Dev/pocketsphinx/../sphinxbase... no
> checking for sphinxbase in /Users/topher/Dev/pocketsphinx/scratch/armv7//Users/topher/Dev/pocketsphinx/../sphinxbase*... no
> checking for SPHINXBASE... no

These paths obviously look a bit messed up. My current directory layout is:
./
/pocketsphinx/
/sphinxbase/

Have I missed a step somewhere?

Thanks.

**Comment by mbait** [comment]
`/Users/topher/Dev/pocketsphinx/scratch/armv7//Users/topher/Dev/pocketsphinx/../sphinxbase`
This is suspicious. Either your OS does not handle ".." as Linux does, or your layout is not like what you have described.

**Comment by anupamme** [comment]
I am facing the same issue. I am using it on os x 10.9.5. What is the fix?

**Comment by christopherredden** [comment]
The build scripts are looking in wrong paths mostly. My path above was correct, my OS supported ".." as Linux does. But since the build scripts were so wrong, and the response above didn't take me seriously, I didn't feel like fixing it and just used OpenEars instead.

If you're dead set on fixing it, just fix the paths it's checking for the libraries in.

**Comment by anupamme** [comment]
okay. I have a question related openears:

my requirement is that we want real time voice to text conversion for audio samples of length around 60 secs. I could use google speech api but it limits to 10-15 secs. So I was looking at sphinx. I looked at openears, and it seems it is only used for offline conversion not real time. Is that correct?

**Comment by christopherredden** [comment]
OpeanEars is just an iOS wrap around PocketSphinx, and yes it supports real-time Voice-to-Text to the same level PocketSphinx does.

**Comment by anupamme** [comment]
Hi topherredden, can I email you offline as I have some queries related to speech to text tools? If yes, what will be your email id.

I am facing issues related to correctness of conversion. I was getting better conversion with some of the other tools so I wanted to check.

**Comment by nshmyrev** [comment]
Fixed in pocketsphinx/pocketsphinx-ios-demo master, thank you for the report.
