### ISSUE TITLE
sphinxbase/prim_type.h missing

### ISSUE THREAD

**Issue by mosesjlee** [cmusphinx/pocketsphinx-ios-demo#11]
These are the steps that I performed based on the readme.

Clone latest copy of sphinxbase and pocketsphinx.
Run autogen.sh on both directories starting sphinxbase
Copy build_iphone.sh into both directory.
Run build_iphone.sh in sphinxbase first
Run build_iphone.sh in pocketsphinx

However when I run the script in the pocketsphinx in blkarray_list.c i get <sphinxbase/prim_type.h> is not found. I verified the header is in /usr/local/include/

Before I tried the build_iphone.sh I was able to successfully make and install both sphinxbase and pocketsphinx

I am running Mac OS 10.11

**Comment by nshmyrev** [comment]
Make sure that sphinxbase folder is named "sphinxbase" and it is in the same folder as "pocketsphinx"
