### ISSUE TITLE
Missing Header Files

### ISSUE THREAD

**Issue by cocoBavan** [cmusphinx/pocketsphinx-ios-demo#13]
Hi, 
I see several header files from PocketSphinx source files are missing in the included headers. For example, ps_alignment.h is missing. But, I believe this header is required. Any clues?

**Comment by nshmyrev** [comment]
I'm sorry, what "included headers" are you talking about. This package is just a build script. Please elaborate.

**Comment by cocoBavan** [comment]
After I built PocketSphinx with this script, I went and looked inside, "bin->arm64->include-> pocketsphinx" folder. 
I expected ps_alignment.h among the headers or at least included in the PocketSphinx.h. 
Not too sure why it was missing there, unless it is not a public api.
I was trying to add [this](https://github.com/cmusphinx/pocketsphinx/blob/master/test/unit/test_alignment.c) feature to [this](https://github.com/tryolabs/TLSphinx).

**Comment by nshmyrev** [comment]
It is not a part of public API, if you want to use alignment, you can copy the header manually.

**Comment by cocoBavan** [comment]
oh ok.. thank you..
