### ISSUE TITLE
Unable to run autogen in pocketsphinx folder

### ISSUE THREAD

**Issue by eaigner** [cmusphinx/pocketsphinx-ios-demo#14]
The README says to run autogen in the pocketsphinx folder, but that is not working. Autogen cannot be run if `sphinxbase` is not found on the system

```
configure: error: in '.../pocketsphinx-master':
configure: error: SphinxBase was not found on your system.
```

**Comment by nshmyrev** [comment]
sphinxbase folder name should be simply sphinxbase, not sphinxbase-master.
