### ISSUE TITLE
Pocketsphinx ps_set_lm take a long time in iOS

### ISSUE THREAD

**Issue by 1Caxz** [cmusphinx/pocketsphinx-ios-demo#17]
Hi guys, I need help!
I try to replicate the Pocketsphinx-android library in swift language on iOS, everything works well except about adding the language model. 
For example, I have about 10 new words already added with "ngram_model_add_word" and then I tried to set the language model with "ps_set_lm", but its take a long time and take 99% CPU usage. But in Android, its only take less than a second. My question is, how to set language model faster and reduce the CPU usage?
```swift
fileprivate func generateNGramModel(words: [String])  {
        let arpaFile = Utilities.getAssetPath()!.appending("\(SEARCH_ID).arpa")
        nGramModel = NGramModel(config: config, logMath: recognizer.getDecoder().getLogMath(), lmFile: arpaFile)
        for word in words {
            nGramModel?.addWord(word: word.lowercased(), weight: 1.7)
        }
        recognizer.getDecoder().setLanguageModel(name: SEARCH_ID, nGramModel: nGramModel!)
}
```

And the method to set the language model:
```swift
open func setLanguageModel(name: String, nGramModel: NGramModel) {
        if ps_set_lm(pointer, name, nGramModel.getPointer())  < 0 {
            print("Set language model failed!")
        }
}
```

**Comment by nshmyrev** [comment]
This is not an issue for pocketsphinx-ios-demo, you already asked the same question on the [forum](https://sourceforge.net/p/cmusphinx/discussion/help/thread/1e90ca8b/?limit=25#1f5e).
