### ISSUE TITLE
ld: library not found for -lblas

### ISSUE THREAD

**Issue by trongdth** [cmusphinx/pocketsphinx-ios-demo#2]
Hello,

Is there anyone know about this "ld: library not found for -lblas"?. Here is my log:

 .libs/fsg_history.o .libs/fsg_lextree.o .libs/fsg_search.o .libs/allphone_search.o .libs/kws_search.o .libs/kws_detections.o .libs/hmm.o .libs/mdef.o .libs/ms_gauden.o .libs/ms_mgau.o .libs/ms_senone.o .libs/ngram_search.o .libs/ngram_search_fwdtree.o .libs/ngram_search_fwdflat.o .libs/phone_loop_search.o .libs/ps_alignment.o .libs/ps_lattice.o .libs/ps_mllr.o .libs/ptm_mgau.o .libs/s2_semi_mgau.o .libs/state_align_search.o .libs/tmat.o .libs/vector.o .libs/pocketsphinx.o   -L/usr/local/lib /usr/local/lib/libsphinxad.dylib /usr/local/lib/libsphinxbase.dylib -lpthread -lm -lblas -llapack  -O3 -arch armv7s -mios-version-min=6.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -arch armv7s -mios-version-min=6.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk   -framework OpenAL -install_name  /Volumes/DATA_1/sample_source/voice_recognition/pocketsphinx/bin/armv7s/lib/libpocketsphinx.3.dylib -compatibility_version 4 -current_version 4.0 -Wl,-single_module
ld: library not found for -lblas
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [libpocketsphinx.la] Error 1
make[1]: **\* [install-recursive] Error 1
make: **\* [install-recursive] Error 1

Thanks

**Comment by nshmyrev** [comment]
Fixed in master
