### ISSUE TITLE
What is build script?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [cmusphinx/pocketsphinx-ios-demo#21]
It says in README.md to "copy build script in sphinxbase folder and in pocketsphinx folder".

What is build script?

**Comment by nshmyrev** [comment]
build_iphone.sh from this repository

**Comment by nshmyrev** [comment]
You'd better check TLSphinx

**Comment by Shinehah-Gnolaum** [comment]
is TLSSpinx a repository on GitHub?
