### ISSUE TITLE
Build failure: No rule to make target `install'

### ISSUE THREAD

**Issue by jamiebullock** [cmusphinx/pocketsphinx-ios-demo#3]
Hi,

If I type from the sphinxbase directory (git 949eb63bf456c576a3f880ec20ba397a11dbc9c1) `../pocketsphinx-ios-demo/build_iphone.sh simulator` on Yosemite.

I get the following error: 

```
building simulator...
/Users/jamie/Documents/sphinxbase/configure --host=simulator-apple-darwin --prefix=/Users/jamie/Documents/sphinxbase/bin/simulator
make: *** No rule to make target `install'.  Stop.
```

Am I doing something wrong here?

**Comment by nshmyrev** [comment]
You need to run this from sphinxbase folder

**Comment by jamiebullock** [comment]
Ah, thanks!
