### ISSUE TITLE
Cross-compiling with libsndfile and libsamplerate

### ISSUE THREAD

**Issue by sdrobert** [cmusphinx/pocketsphinx-ios-demo#5]
Hi Nikolay,

I think that the current autoconf script doesn't distinguish between OSX x86_64 and simulator x86_64. That means that if you try `./build_iphone.sh x86_64` on an x86_64 machine which has access to libsamplerate and libsndfile, you'll get a nice linker error.

Thanks,
Sean

**Comment by nshmyrev** [comment]
Hi Sean

I've just removed libsamplerate and libsndfile altogether yesterday. Could you please update and test again? The problem should not be relevant now.

**Comment by sdrobert** [comment]
Thanks for the quick response. Sorry, I updated a couple of days ago, so I just assumed I was on the latest version :( I'll eat my big slice of humble pie.

While I'm doing that, please note that since you changed the autoconf flag `--without-swig-python` to `--with-python`, this script needs minor tailoring for the repo version. Otherwise you get a grisly error about python.

Cheers,
Sean

**Comment by nshmyrev** [comment]
Changed python option, thanks!
