### ISSUE TITLE
ld: library not found for -lblas Still here.

### ISSUE THREAD

**Issue by danoli3** [cmusphinx/pocketsphinx-ios-demo#6]
https://github.com/cmusphinx/pocketsphinx-ios-demo/issues/2 is Not fixed.

```
ld: library not found for -lblas
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpocketsphinx.la] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

Traced it to this:
`configure: WARNING: unrecognized options: --without-lapack`

Also an additional note, could you detail the process / where to locate the build script. This happened with the following assumptions: (Maybe a good idea to add this to the repo README.md)
- `/pocketsphinx-master` <- folder with current repo from https://github.com/cmusphinx/pocketsphinx
- https://github.com/cmusphinx/sphinxbase  extracted into `/pocketsphinx-master` folder
- `./build_iphone.sh` located in `/pocketsphinx-master/build_iphone.sh`

**Comment by danoli3** [comment]
@nshmyrev any idea why? I thought maybe because the --without- looks for a package... if it doesn't know what that package is it may fail... so I did a homebrew install of lapack to see if that fixed it, no luck there.

**Comment by nshmyrev** [comment]
warning is expected.

As for the error, you probably want to provide full build/configure log including sphinxbase log. It should take -lblas from somewhere.

**Comment by danoli3** [comment]
Alas, it was my misunderstanding of the build folder locations. 

Mind if I make a PR to the readme describing how to use this script more thoroughly.
