### ISSUE TITLE
build question

### ISSUE THREAD

**Issue by matthewchung74** [cmusphinx/pocketsphinx-ios-demo#8]
I'm stuck on the build script and was hoping you might be able to help. when I run ./build_iphone.sh, it gets stuck on line 55 because configure does not exist in that directory.

```
Desktop/sphinx/pocketsphinx-ios-demo/configure: No such file or directory
```

i have pocketsphinx-ios-demo     and sphinxbase in the same directory and am running ./build_iphone.sh from pocketsphinx-ios-demo .  any help is appreciated.

**Comment by nshmyrev** [comment]
You need to run autogen.sh to create configure.

**Comment by matthewchung74** [comment]
to get things working, i had to do this  ../pocketsphinx-ios-demo/build_iphone.sh from the sphinxbase directory. is that how you intended for it to work?

**Comment by nshmyrev** [comment]
yes
