### ISSUE TITLE
problem with integration

### ISSUE THREAD

**Issue by matthewchung74** [cmusphinx/pocketsphinx-ios-demo#9]
nshmyrev,

do you have a sample xcode project where you use the pocketsphinx-ios-demo? I built the project with your scripts, and then tried importing the x86_64 directory for a test on the simulator. After removing the reference to the the share folder, I put 

```
#include <pocketsphinx.h>
```

in the bridging header, trying to follow the instructions here - http://cmusphinx.sourceforge.net/wiki/tutorialpocketsphinx  Unfortunately, I realized there was not pocketsphinx.h header generated. Anyways, do you have any advice or a sample xcode project with the libraries added? I'm having a hard time matching the build to the docs on teh cmusphinx website.

**Comment by nshmyrev** [comment]
pocketsphinx.h is a part of pocketsphinx sources. It is not generated, you just include headers from the pocketsphinx and sphinxbase into the project.
